### ISSUE TITLE
New Clojars release?

### ISSUE THREAD

**Issue by stefanroex** [walmartlabs/schematic#8]
I've updated this issue to better reflect my question, didn't look carefully enough how 1.2.0 and master differ 😅 .

There is an issue with `subconfig-for-components` in 1.2.0 which is fixed in master. The old implementation doesn't track which components are seen and it's possible that the list of `ref-ids` in the loop keeps getting bigger and bigger resulting in a StackOverflowError.

So perhaps it's nice to push a new version of Schematic to Clojars? thanks!

---
Original:

~~We've bumped into an issue today with schematic and where surpriced to see that the code published to clojuars under version 1.2.0 seems to be an older version.~~

~~You can check this by checking the .m2 directory and checking the contents of schematic.clj which includes:~~

```clojure
(defn ^:no-doc subconfig-for-components
  "Returns a map of just the given components and their transitive dependencies"
  [system-config component-ids]
  (let [dep-graph (ref-dependency-graph system-config)]
    (loop [ref-ids component-ids deps (set component-ids)]
      (if-let [ref-id (first ref-ids)]
        (let [new-deps (get-in dep-graph [:dependencies ref-id])]
          (recur (concat (rest ref-ids) new-deps) (into deps new-deps)))
        (select-keys system-config deps)))))
```

~~This seems to be the implementation of [version 1.1.0](https://github.com/walmartlabs/schematic/blob/v1.1.0/src/com/walmartlabs/schematic.clj#L255) whereas 1.2.0 looks like [this](https://github.com/walmartlabs/schematic/blob/v1.2.0/src/com/walmartlabs/schematic.clj#L287). The `project.clj` in the .m2 dir does seem to mention 1.2.0.~~

~~We've fixed our issue by depending on a github sha via tools.deps copying the code to our project, but I hope you're able to fix the Clojars release 😃 .~~

**Comment by hlship** [comment]
Thanks for the reminder.  I should be able to do so soon. No reason not to.

**Comment by hlship** [comment]
Just pushed to clojars.
